name: Deploy to Kubernetes
on:
  push:
    branches:
      - main

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  deploy:
    runs-on: "self-hosted"  # (optional) name of the runner labels, groups 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy App(Deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f kubernetes/memos-deployment.yml
          
      # - name: Deploy Service
      #   uses: actions-hub/kubectl@master
      #   with:
      #     args: apply -f kubernetes/service.yml
          
      # - name: Deploy Ingress
      #   uses: actions-hub/kubectl@master
      #   with:
      #     args: apply -f kubernetes/ingress.yml        